use serde_json::{Value, json};

use crate::model::{OutboundSpec, Server, StreamSettings};

/// Generate a full Xray config JSON for `server`, with local SOCKS + HTTP inbounds.
pub fn generate(server: &Server, socks_port: u16, http_port: u16) -> Value {
    let mut config = json!({
        "log": { "loglevel": "warning" },
        "inbounds": [
            {
                "tag": "socks-in",
                "listen": "127.0.0.1",
                "port": socks_port,
                "protocol": "socks",
                "settings": { "auth": "noauth", "udp": true },
                "sniffing": { "enabled": true, "destOverride": ["http", "tls"] }
            },
            {
                "tag": "http-in",
                "listen": "127.0.0.1",
                "port": http_port,
                "protocol": "http",
                "sniffing": { "enabled": true, "destOverride": ["http", "tls"] }
            }
        ],
    });

    match &server.spec {
        OutboundSpec::XrayProfile {
            proxy_outbounds,
            balancers,
            burst_observatory,
            balancer_tag,
        } => {
            let mut outbounds = proxy_outbounds.clone();
            outbounds.push(json!({ "protocol": "freedom", "tag": "direct" }));
            outbounds.push(json!({ "protocol": "blackhole", "tag": "block" }));
            config["outbounds"] = Value::Array(outbounds);
            config["routing"] = json!({
                "domainStrategy": "IPIfNonMatch",
                "rules": [
                    { "type": "field", "ip": ["geoip:private"], "outboundTag": "direct" },
                    { "type": "field", "network": "tcp,udp", "balancerTag": balancer_tag }
                ],
                "balancers": balancers
            });
            if let Some(observatory) = burst_observatory {
                config["burstObservatory"] = observatory.clone();
            }
        }
        _ => {
            config["outbounds"] = json!([
                outbound(server),
                { "protocol": "freedom", "tag": "direct" },
                { "protocol": "blackhole", "tag": "block" }
            ]);
            config["routing"] = json!({
                "domainStrategy": "IPIfNonMatch",
                "rules": [
                    { "type": "field", "ip": ["geoip:private"], "outboundTag": "direct" }
                ]
            });
        }
    }

    config
}

fn outbound(server: &Server) -> Value {
    let addr = &server.address;
    let port = server.port;
    match &server.spec {
        OutboundSpec::Vless {
            uuid,
            encryption,
            stream,
        } => json!({
            "tag": "proxy",
            "protocol": "vless",
            "settings": { "vnext": [ {
                "address": addr,
                "port": port,
                "users": [ trim_obj(json!({
                    "id": uuid,
                    "encryption": encryption,
                    "flow": stream.flow
                })) ]
            } ] },
            "streamSettings": stream_settings(stream)
        }),
        OutboundSpec::Vmess {
            uuid,
            alter_id,
            security,
            stream,
        } => json!({
            "tag": "proxy",
            "protocol": "vmess",
            "settings": { "vnext": [ {
                "address": addr,
                "port": port,
                "users": [ { "id": uuid, "alterId": alter_id, "security": security } ]
            } ] },
            "streamSettings": stream_settings(stream)
        }),
        OutboundSpec::Trojan { password, stream } => json!({
            "tag": "proxy",
            "protocol": "trojan",
            "settings": { "servers": [ trim_obj(json!({
                "address": addr,
                "port": port,
                "password": password,
                "flow": stream.flow
            })) ] },
            "streamSettings": stream_settings(stream)
        }),
        OutboundSpec::Shadowsocks { method, password } => json!({
            "tag": "proxy",
            "protocol": "shadowsocks",
            "settings": { "servers": [ {
                "address": addr,
                "port": port,
                "method": method,
                "password": password
            } ] }
        }),
        OutboundSpec::Socks { username, password } => json!({
            "tag": "proxy",
            "protocol": "socks",
            "settings": { "servers": [ socks_http_server(addr, port, username, password) ] }
        }),
        OutboundSpec::Http { username, password } => json!({
            "tag": "proxy",
            "protocol": "http",
            "settings": { "servers": [ socks_http_server(addr, port, username, password) ] }
        }),
        OutboundSpec::XrayProfile { .. } => {
            unreachable!("composite profiles are generated by generate")
        }
    }
}

fn socks_http_server(addr: &str, port: u16, user: &Option<String>, pass: &Option<String>) -> Value {
    let mut server = json!({ "address": addr, "port": port });
    if let (Some(u), Some(p)) = (user, pass) {
        server["users"] = json!([ { "user": u, "pass": p } ]);
    }
    server
}

fn stream_settings(s: &StreamSettings) -> Value {
    let mut v = json!({ "network": if s.network.is_empty() { "tcp" } else { &s.network } });

    match s.network.as_str() {
        "ws" => {
            v["wsSettings"] = trim_obj(json!({
                "path": s.path,
                "headers": s.host.as_ref().map(|h| json!({ "Host": h }))
            }));
        }
        "grpc" => {
            v["grpcSettings"] = trim_obj(json!({
                "serviceName": s.service_name.clone().or_else(|| s.path.clone())
            }));
        }
        "xhttp" | "splithttp" => {
            v["xhttpSettings"] = trim_obj(json!({
                "path": s.path,
                "host": s.host,
                "mode": "auto"
            }));
        }
        "h2" | "http" => {
            v["httpSettings"] = trim_obj(json!({
                "path": s.path,
                "host": s.host.as_ref().map(|h| json!([h]))
            }));
        }
        "tcp" if s.header_type.as_deref() == Some("http") => {
            v["tcpSettings"] = json!({ "header": { "type": "http" } });
        }
        _ => {}
    }

    match s.security.as_str() {
        "tls" => {
            v["security"] = json!("tls");
            // `allowInsecure` is deliberately not emitted: Xray 26.x removed it
            // ("has been removed and migrated to pinnedPeerCertSha256") and
            // rejects the whole config when it is true, so emitting it turns an
            // insecure-TLS server into a core that refuses to start. A pin is
            // the only remaining way to accept an otherwise-untrusted cert.
            v["tlsSettings"] = trim_obj(json!({
                "serverName": s.sni,
                "alpn": s.alpn,
                "fingerprint": s.fingerprint,
                "pinnedPeerCertSha256": s.pin_sha256
            }));
        }
        "reality" => {
            v["security"] = json!("reality");
            v["realitySettings"] = trim_obj(json!({
                "serverName": s.sni,
                "fingerprint": s.fingerprint,
                "publicKey": s.public_key,
                "shortId": s.short_id,
                "spiderX": s.spider_x
            }));
        }
        _ => {}
    }

    v
}

/// Drop null values from a JSON object (Xray rejects some explicit nulls).
fn trim_obj(v: Value) -> Value {
    match v {
        Value::Object(map) => Value::Object(
            map.into_iter()
                .filter(|(_, val)| !val.is_null())
                .map(|(k, val)| (k, trim_obj(val)))
                .collect(),
        ),
        other => other,
    }
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::generate;
    use crate::model::{OutboundSpec, Protocol, Server, StreamSettings};

    #[test]
    fn balanced_profile_keeps_local_inbounds_and_safe_routing() {
        let server = Server {
            id: "profile".to_string(),
            name: "Auto".to_string(),
            protocol: Protocol::Vless,
            address: "one.example".to_string(),
            port: 443,
            transport_label: "xray + balanced (2)".to_string(),
            country: None,
            spec: OutboundSpec::XrayProfile {
                proxy_outbounds: vec![
                    json!({"tag":"proxy","protocol":"vless","settings":{}}),
                    json!({"tag":"proxy-2","protocol":"vless","settings":{}}),
                ],
                balancers: vec![json!({"tag":"balance","selector":["proxy"]})],
                burst_observatory: Some(json!({"subjectSelector":["proxy"]})),
                balancer_tag: "balance".to_string(),
            },
            link: None,
            latency_ms: None,
        };

        let config = generate(&server, 10808, 10809);
        assert_eq!(config["inbounds"][0]["port"], 10808);
        assert_eq!(config["outbounds"].as_array().map(Vec::len), Some(4));
        assert_eq!(config["routing"]["rules"][0]["ip"][0], "geoip:private");
        assert_eq!(config["routing"]["rules"][1]["balancerTag"], "balance");
        assert_eq!(config["burstObservatory"]["subjectSelector"][0], "proxy");
    }

    fn tls_vless(allow_insecure: bool, pin: Option<&str>) -> Server {
        let stream = StreamSettings {
            network: "tcp".to_string(),
            security: "tls".to_string(),
            sni: Some("example.com".to_string()),
            allow_insecure,
            pin_sha256: pin.map(str::to_string),
            ..Default::default()
        };
        Server {
            id: "s".to_string(),
            name: "S".to_string(),
            protocol: Protocol::Vless,
            address: "example.com".to_string(),
            port: 443,
            transport_label: "vless + tls".to_string(),
            country: None,
            spec: OutboundSpec::Vless {
                uuid: "b831381d-6324-4d53-ad4f-8cda48b30811".to_string(),
                encryption: "none".to_string(),
                stream,
            },
            link: None,
            latency_ms: None,
        }
    }

    /// Xray 26.x rejects the whole config when `allowInsecure` is true, so a
    /// server that asks for it must still produce a config the core will start.
    #[test]
    fn allow_insecure_is_never_emitted() {
        for insecure in [true, false] {
            let config = generate(&tls_vless(insecure, None), 10808, 10809);
            let tls = &config["outbounds"][0]["streamSettings"]["tlsSettings"];
            assert!(
                tls.get("allowInsecure").is_none(),
                "allowInsecure leaked with insecure={insecure}: {tls}"
            );
            assert_eq!(tls["serverName"], "example.com");
        }
    }

    #[test]
    fn certificate_pin_is_emitted_as_a_bare_hex_string() {
        let pin = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
        let config = generate(&tls_vless(true, Some(pin)), 10808, 10809);
        let tls = &config["outbounds"][0]["streamSettings"]["tlsSettings"];
        // A bare string, not an array: Xray 26.x fails to decode the array form.
        assert_eq!(tls["pinnedPeerCertSha256"], json!(pin));
    }

    #[test]
    fn absent_pin_leaves_the_key_out() {
        let config = generate(&tls_vless(false, None), 10808, 10809);
        let tls = &config["outbounds"][0]["streamSettings"]["tlsSettings"];
        assert!(tls.get("pinnedPeerCertSha256").is_none(), "{tls}");
    }
}
